server:
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# MinIO 配置
minio:
  # MinIO 服务地址
  endpoint: http://localhost:9000
  # 账号
  accessKey: minioadmin
  # 密码
  secretKey: minioadmin123
  # 默认桶名称（不存在会自动创建）
  bucketName: pichub-bucket
spring:
  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  # Spring Boot 2.7+ 必须加（解决 pathpattern 问题）
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: PicHub
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picHub_db
    username: root
    password: 123456
  # Redis 配置
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    timeout: 5000
  # Session 配置
  session:
    store-type: redis
    # session 30 天后过期
    timeout: 2592000
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  # 空间图片分表
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
# Knife4j 配置
knife4j:
  enable: true                    # 开启增强功能
  production: false               # 生产环境设为 true 可禁用文档
  basic:
    enable: false                 # 是否开启认证（可选）
    username: admin
    password: 123456

  # 文档信息配置
  setting:
    language: zh_cn               # 中文
    swagger-model-name: 实体类列表
    enableSwaggerModels: true
    enableDocumentManage: true

